name: downmerge
on:
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ steps.generate-token.outputs.token }}
      - name: merge main to develop
        run: |
          git remote update
          git fetch
          git checkout develop
          git merge main
          git push
