name: galeria

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 0'

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  pipeline:
    uses: ./.github/workflows/location.yaml
    with:
      location: galeria
    secrets: inherit
