name: moritzbastei

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 2'

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  pipeline:
    uses: ./.github/workflows/location.yaml
    with:
      location: moritzbastei
    secrets: inherit
