name: Create release and build website

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'locations/**'
      - 'site/**'
      - '.github/workflows/site-release.yaml'
permissions:
  contents: write
  packages: read
  pull-requests: read

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      version: ${{ steps.changelog.outputs.tag }}
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: "true"
          skip-git-pull: "true"
          skip-tag: "true"
  build:
    needs: get-version
    if: ${{ needs.get-version.outputs.skipped == 'false' }}
    uses: ./.github/workflows/site.yaml
    with:
      version: ${{ needs.get-version.outputs.version }}
  create-version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: "true"
          skip-git-pull: "true"
          skip-tag: "false"
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}