name: upmerge
on:
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: develop
          token: ${{ steps.generate-token.outputs.token }}
      - name: merge develop to main
        run: |
          git checkout main
          git merge develop
          git push
