name: upmerge
on:
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ steps.generate-token.outputs.token }}
      - name: merge develop to main
        run: |
          if ! git config user.name > /dev/null; then
            git config user.name "holygrolli"
          fi
          if ! git config user.email > /dev/null; then
            git config user.email "holygrolli@users.noreply.github.com"
          fi
          git remote update
          git fetch
          git checkout main
          git merge develop
          git push
